services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - ecosystem
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # カスタム設定を使用する場合
      - ./html:/usr/share/nginx/html:ro  # 静的なHTMLファイルを提供する場合
